# Settings.yml
---
conf.py:
  project: TypoScript Reference
  copyright: 2000-2014
  version: 6.2
  release: 6.2
  intersphinx_mapping:
    t3cmsapi:
    - http://typo3.org/api/typo3cms/
    - null
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3tssyntax:
    - http://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/
    - null
    t3tsconfig:
    - http://docs.typo3.org/typo3cms/TSconfigReference
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-Typoscript
    github_branch: latest

  latex_documents:
  - - Index
    - t3tsref.tex
    - Typoscript Reference
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}

...
